[mypy]
exclude=^(\.cache/|\.idea/|\.vscode/|logs/)*$


# Required to catch inconsistent return types
check_untyped_defs = true

# Ignore everything else to stay minimal
disable_error_code = index, arg-type
disallow_untyped_defs = false
disallow_any_unimported = false
disallow_any_expr = false
disallow_any_decorated = false
warn_unused_ignores = false
warn_return_any = false
no_implicit_optional = false
strict_optional = false
ignore_missing_imports = true
follow_imports = skip

# Keep output clean
show_error_codes = true

[mypy-requests]
ignore_missing_imports = true
