# coding: utf-8
# Copyright (c) Huawei Technologies Co., Ltd. 2026. All rights reserved.
import inspect
from typing import Optional
from openjiuwen.core.runner.resources_manager.abstract_manager import AbstractManager
from openjiuwen.core.runner.resources_manager.base import SysOperationProvider
from openjiuwen.core.sys_operation.sys_operation import SysOperation, SysOperationCard


class SysOperationMgr(AbstractManager[SysOperation]):
    """Manager for SysOperation instances"""

    def __init__(self):
        super().__init__()

    def add_sys_operation(self, sys_operation_id: str, sys_operation: SysOperationProvider):
        """
        Register a callable SysOperationProvider with a unique ID.

        Args:
            sys_operation_id: Unique string identifier for the SysOperationProvider
            sys_operation: Callable SysOperationProvider to be registered
        """
        self._register_resource_provider(sys_operation_id, sys_operation)

    def remove_sys_operation(self, sys_operation_id: str) -> Optional[SysOperationProvider]:
        """
        Unregister and remove the SysOperationProvider by its unique ID.

        Args:
            sys_operation_id: Unique string identifier of the SysOperationProvider to remove

        Returns:
            The removed callable SysOperationProvider if found; None otherwise
        """
        self._unregister_resource_provider(sys_operation_id)

    async def get_sys_operation(self, sys_operation_card: SysOperationCard) -> Optional[SysOperation]:
        """
        Retrieve the SysOperation instance via the registered SysOperationProvider.

        Args:
            sys_operation_card: Unique identifier of the target SysOperationProvider

        Returns:
            SysOperation instance generated by the SysOperationProvider if found; None otherwise
        """
        resource_provider = self._providers.get(sys_operation_card.id)
        if not resource_provider:
            return None
        if inspect.iscoroutinefunction(resource_provider):
            return await resource_provider(sys_operation_card)
        else:
            return resource_provider(sys_operation_card)
