logging:
  level: INFO
  backup_count: 20
  max_bytes: 20971520
  format: '%(asctime)s | %(log_type)s | %(filename)s | %(lineno)d | %(funcName)s | %(trace_id)s | %(levelname)s | %(message)s'
  log_file: "run/jiuwen.log"
  output: ["console", "file"]
  interface_log_file : "interface/jiuwen_interface.log"
  prompt_builder_interface_log_file: "interface/jiuwen_prompt_builder_interface.log"
  performance_log_file: "performance/jiuwen_performance.log"
  interface_output: ["console", "file"] # 同时输出到控制台和文件
  performance_output: ["console", "file"]
  log_path: "./logs/"

plugin:
  store: "gaussdb"
  cache_maxsize: "1000"
  default_dir: "./plugins"
  recall:
    emb_class:
    emb_service_url: ""
    app_code: ""
    emb_dim: 256
    infer_fields: [ "func_description" ]

prompt:
  default_dir: "./prompts"

executor:
  worker:
    timeout: 300
    conn_timeout: 300
    read_timeout: 5
    resume_interval: 15000
    max_retry: 2
    thread_num: 100
    stream_out_mode: mq

planner_config:
  finish_triggers:
    - "yes"
    - "是"

rails:
  custom_rails_path: #自定义护栏路径