version: '1.0'
name: pipeline-20250806
displayName: agentcore
triggers:
  trigger: auto
  pr:
    branches:
      prefix:
        - develop
stages:
  - name: stage-c019e95c
    displayName: 单元测试
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: ut@python
        name: unit_test_python
        displayName: Python 单元测试
        pythonVersion: '3.11'
        commands:
          - '# Python单元测试默认命令'
          - pip install uv -i https://mirrors.aliyun.com/pypi/simple/
          - uv sync --group dev
          - uv run pytest --html=report/index.html
        report:
          path: report
          index: index.html
        checkpoints:
          - key: TestPassRate
            value: 100
            logicalOperator: '&&'
            relationalOperator: '>='
        caches: []
        notify: []
        strategy:
          retry: '0'
