version: '1.0'
name: pipeline-20250806
displayName: agentcore
triggers:
  trigger: auto
  pr:
    branches:
      include:
        - (develop|release\/0\.3\.0|release\/0\.4\.0)
stages:
  - name: stage-c019e95c
    displayName: 单元测试
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: ut@python
        name: unit_test_python
        displayName: Python 单元测试
        pythonVersion: '3.11'
        commands:
          - apt-get update -y
          - '# 安装 SQLite3 开发库'
          - apt-get install -y libsqlite3-dev
          - pip3 install uv -i https://mirrors.aliyun.com/pypi/simple/
          - uv sync --group dev --all-extras
          - uv sync --all-extras
          - uv run pytest
          - /usr/local/python3.11/bin/uv sync --group dev
          - /usr/local/python3.11/bin/uv sync --all-extrasecho "=== Syncing dependencies with uv ==="
          - /usr/local/python3.11/bin/uv run pytest
        report:
          path: report
          index: index.html
        checkpoints:
          - key: TestPassRate
            value: 80
            logicalOperator: '&&'
            relationalOperator: '>='
        caches: []
        notify: []
        strategy:
          retry: '0'
